/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
start:10250431.56120726
Selecting parsl_config: {'label': 'expanse-htex', 'max_workers_per_node': 128, 'provider': LocalProvider(
    channel=LocalChannel(
        envs={}, 
        script_dir=None, 
        userhome='/home/yadunand/flox-scaling-tests/parsl-tests'
    ), 
    cmd_timeout=30, 
    init_blocks=1, 
    launcher=SrunLauncher(debug=True, overrides='--exclude=$SLURMD_NODENAME'), 
    max_blocks=1, 
    min_blocks=0, 
    move_files=None, 
    nodes_per_block=1, 
    parallelism=1, 
    worker_init='source ~/setup_parsl_test_env.sh; export PYTHONPATH=/home/yadunand/flox-scaling-tests/parsl-tests:$PYTHONPATH'
)}
priming_done:10250547.070535656
federated_fit::sync:   0%|          | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/yadunand/flox-scaling-tests/parsl-tests/test.py", line 137, in <module>
    main(parsed_args)
  File "/home/yadunand/flox-scaling-tests/parsl-tests/test.py", line 89, in main
    flox.federated_fit(
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/flox/runtime/fit.py", line 136, in federated_fit
    trained_module, history = process.start(debug_mode=debug_mode)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/flox/runtime/process/process_sync_v2.py", line 75, in start
    step_result = self.step().result()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/parsl/executors/high_throughput/executor.py", line 520, in _queue_management_worker
    s.reraise()
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/parsl/app/errors.py", line 118, in reraise
    raise v
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/bin/process_worker_pool.py", line 760, in worker
    result = execute_task(req['buffer'], mpi_launcher=mpi_launcher)
^^^^^^^^^^^^^^^
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/bin/process_worker_pool.py", line 591, in execute_task
    f, args, kwargs, resource_spec = unpack_res_spec_apply_message(bufs, user_ns, copy=False)
      ^^^^^^^^^^^^^^^^^
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/parsl/serialize/facade.py", line 99, in unpack_res_spec_apply_message
    func, args, (kwargs, resource_spec) = unpack_apply_message(packed_buffer, user_ns=user_ns, copy=copy)
      ^^^^^^^^^^^^^^^^^
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/parsl/serialize/facade.py", line 93, in unpack_apply_message
    return [deserialize(buf) for buf in unpack_buffers(packed_buffer)]
      ^^^^^^^^^^^^^^^^^
  File "/home/yadunand/miniconda3/envs/parsl_py3.11/lib/python3.11/site-packages/parsl/serialize/facade.py", line 188, in unpack_buffers
    s_length, buf = packed_buffer.split(b'\n', 1)
  ^^^^^^^^^^^^^^^^^
MemoryError
